---
variables:
  TF_MIN_VERSION: "1.2"
  AZURERM_PROVIDER_MIN_VERSION: "3.22"

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - project: 'claranet/projects/cloud/azure/terraform/ci'
    ref: AZ-989_fix_tflint_report
    file: '/pipeline.yml'
...
