# Generic naming variables
variable "name_prefix" {
  description = "Optional prefix for the generated name."
  type        = string
  default     = ""
}

variable "name_suffix" {
  description = "Optional suffix for the generated name."
  type        = string
  default     = ""
}

# Custom naming override
variable "custom_name" {
  description = "Custom Private Endpoint name, generated if not set."
  type        = string
  default     = ""
}

variable "nic_custom_name" {
  description = "Custom network interface name of the Private Endpoint, generated by Azure if not set."
  type        = string
  default     = null
}

variable "private_dns_zone_group_custom_name" {
  description = "Custom Private DNS Zone Group name, generated if not set."
  type        = string
  default     = ""
}

variable "private_service_connection_custom_name" {
  description = "Custom Private Service Connection name, generated if not set."
  type        = string
  default     = ""
}
